### PR TITLE
Fix frotz/dumb linker error: resolves #44

### LINKED ISSUE #44: linker issue: multiple definition of - first defined here
I'm having difficulty installing jericho, a dependency I need for TextWorld. Specifically, I'm having trouble building that `frotz` library. `cd`-ing into the frotz directory and running `make library -j4` gives this linker error:
```
    /usr/bin/ranlib src/ztools.a
    /usr/bin/ld: src/dumb/dumb_input.o:(.bss+0xa8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
    /usr/bin/ld: src/dumb/dumb_input.o:(.bss+0x0): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_output.o:(.bss+0x0): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_output.o:(.bss+0xa8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
    /usr/bin/ld: src/dumb/dumb_pic.o:(.bss+0x0): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_pic.o:(.bss+0xa8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
    /usr/bin/ld: src/dumb/dumb_blorb.o:(.bss+0x40): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here
    /usr/bin/ld: src/dumb/dumb_blorb.o:(.bss+0xe8): multiple definition of `do_more_prompts'; src/dumb/dumb_init.o:(.bss+0xa8): first defined here
```
For reference:
- running `5.12.8-arch1-1`
- `gcc --version = gcc (GCC) 11.1.0`
- `make --version = GNU Make 4.3`
- I have all required packages installed

I have attempted to do the following in an attempt to resolve this:
- downgrading to different `gcc` and `make` versions, with no success there. I only downgraded to `gcc-7` and `gcc-8`
- resolving definitions in code by including various `extern` decorators. I reached a state of the code that allowed me to compile, but then I ran it with TextWorld and the game crashed and it couldn't find the variable definitions. So basically I couldn't successfully alter the code to find this issue. I didn't do an extensive code read/fix though, and my `C` is a little rusty. This is super hacky and it makes sense why it fails to run properly.
- Downgrading to different versions of Jericho. This linker issue persists for all versions as far as I can tell

Is this an issue that others have encountered or is there something about my system that is causing this that I can fix?

Thanks

### PR DESCRIPTION
**Pull request by MathieuTuli**
- This commit adds necessary `extern` declarations to variable names to
avoid a linker error on modern gcc compilers. Update follows changes in
the update frotz library
(https://gitlab.com/DavidGriffith/frotz/-/tree/master/src/dumb)

### CODE REVIEW

**Comment by MarcCote** [comment]
On my system (with gcc version 7.5.0)
```bash
OSError: /tmp/tmp9pgwtgt5/libfrotz.so: undefined symbol: f_setup
```

when running
> pytest tests

File: frotz/src/dumb/dumb_init.c [hunk 1]
```diff
@@ -23,7 +23,7 @@
 #include "dumb_frotz.h"
 #include "dumb_blorb.h"
 
-f_setup_t f_setup;
+extern f_setup_t f_setup;
```
Comment (MarcCote) [inline frotz/src/dumb/dumb_init.c:26]: I think this one shouldn't be `extern`. According to your log in issue #44 
> /usr/bin/ld: src/dumb/dumb_input.o:(.bss+0x0): multiple definition of `f_setup'; src/dumb/dumb_init.o:(.bss+0x0): first defined here

`dumb_init.o` seems to contain the first definition.

**Review by MarcCote — CHANGES_REQUESTED** [review]

File: frotz/src/dumb/dumb_init.c (hunk 1 above)
Comment (MarcCote) [reply frotz/src/dumb/dumb_init.c:26]: PS: it makes `pytest tests` happy on my machine.

Comment (MathieuTuli) [reply frotz/src/dumb/dumb_init.c]: Yes I just realized the same thing, no complaints on my machine also. Commit made.

**Review by MarcCote — APPROVED** [review]

**Review by mhauskn — APPROVED** [review]
Looks good, thanks for creating this PR!
